import { JSDOM } from "jsdom";
import { beforeEach, afterEach, expect, it } from "vitest";
import { createMovableWindow, createModalFocus } from "../public/house-shell.js";
let dom: JSDOM;
beforeEach(()=>{dom=new JSDOM(`<button id="launch">Chat</button><aside id="chat" hidden><header id="handle" tabindex="0"><button id="collapse">Collapse</button></header><div id="body"><textarea id="draft"></textarea></div><button id="resize" aria-label="Resize chat">Resize</button></aside><section id="modal" hidden><button id="first">Close</button><input id="last"></section>`,{url:"http://localhost"});});
afterEach(()=>dom.window.close());
const el=(id:string)=>dom.window.document.getElementById(id)!;
function controller(){return createMovableWindow({window:dom.window,element:el("chat"),handle:el("handle"),body:el("body"),collapse:el("collapse"),resize:el("resize"),onChange:()=>{}});}
it("keeps the composer draft when chat is collapsed, hidden and reopened",()=>{const chat=controller();chat.open(el("launch"));(el("draft") as HTMLTextAreaElement).value="My multiline\ndraft";el("collapse").click();expect(el("body").hidden).toBe(true);chat.close();chat.open(el("launch"));expect((el("draft") as HTMLTextAreaElement).value).toBe("My multiline\ndraft");expect(el("body").hidden).toBe(false);chat.dispose();});
it("moves the chat with keyboard controls and bounds the title within the viewport",()=>{const chat=controller();chat.open(el("launch"));for(let i=0;i<100;i++)el("handle").dispatchEvent(new dom.window.KeyboardEvent("keydown",{key:"ArrowRight",bubbles:true}));expect(parseFloat(el("chat").style.left)).toBeLessThanOrEqual(dom.window.innerWidth-240);el("handle").dispatchEvent(new dom.window.KeyboardEvent("keydown",{key:"ArrowLeft",bubbles:true}));expect(parseFloat(el("chat").style.left)).toBeGreaterThanOrEqual(8);chat.dispose();});
it("supports pointer drag without treating its header buttons as drag handles",()=>{const chat=controller();chat.open(el("launch"));const pointer=(type:string,x:number,y:number,target=el("handle"))=>{const event=new dom.window.MouseEvent(type,{clientX:x,clientY:y,bubbles:true});Object.defineProperty(event,"pointerId",{value:1});target.dispatchEvent(event);};pointer("pointerdown",30,30);pointer("pointermove",130,100);pointer("pointerup",130,100);expect(parseFloat(el("chat").style.left)).toBeGreaterThan(8);const left=el("chat").style.left;pointer("pointerdown",130,100,el("collapse"));pointer("pointermove",300,200);pointer("pointerup",300,200);expect(el("chat").style.left).toBe(left);chat.dispose();});
it("keeps all chat controls reachable after a narrow viewport resize",()=>{const chat=controller();chat.open(el("launch"));Object.defineProperty(dom.window,"innerWidth",{value:390,configurable:true});Object.defineProperty(dom.window,"innerHeight",{value:320,configurable:true});dom.window.dispatchEvent(new dom.window.Event("resize"));expect(parseFloat(el("chat").style.width)).toBeLessThanOrEqual(374);expect(parseFloat(el("chat").style.height)).toBeLessThanOrEqual(304);expect(parseFloat(el("chat").style.left)+parseFloat(el("chat").style.width)).toBeLessThanOrEqual(382);chat.dispose();});
it("resizes the window with native keyboard controls without losing text",()=>{const chat=controller();chat.open(el("launch"));const width=parseFloat(el("chat").style.width);(el("draft") as HTMLTextAreaElement).value="Draft";el("resize").dispatchEvent(new dom.window.KeyboardEvent("keydown",{key:"ArrowRight",bubbles:true}));expect(parseFloat(el("chat").style.width)).toBe(width+16);expect((el("draft") as HTMLTextAreaElement).value).toBe("Draft");chat.dispose();});
it("isolates chat keys, wheel and paste from world shortcuts",()=>{const chat=controller();chat.open(el("launch"));let leaked=0;for(const type of ["keydown","wheel","paste"]){dom.window.document.addEventListener(type,()=>leaked++);el("draft").dispatchEvent(new dom.window.Event(type,{bubbles:true,cancelable:true}));}expect(leaked).toBe(0);chat.dispose();});
it("traps modal tab focus and restores its native launcher on close",()=>{const focus=createModalFocus(el("modal"),dom.window.document);el("launch").focus();el("modal").hidden=false;focus.open(el("launch"));expect(dom.window.document.activeElement).toBe(el("first"));el("last").focus();el("last").dispatchEvent(new dom.window.KeyboardEvent("keydown",{key:"Tab",bubbles:true,cancelable:true}));expect(dom.window.document.activeElement).toBe(el("first"));el("modal").hidden=true;focus.close();expect(dom.window.document.activeElement).toBe(el("launch"));focus.dispose();});
